global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<UNRAID_IP>:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['<UNRAID_IP>:8080']
